version: 2.1
commands:
  print_pipeline_id:
    description:
    steps:
      - run: echo ${CIRCLE_WORKFLOW_ID}
jobs:
  reusable_command:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - print_pipeline_id
  get_ec2_instance_ips:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run:
          command: |
            touch ~/inventory
            echo [all] > ~/inventory
            aws ec2 describe-instances \
              --query 'Reservations[*].Instances[*].PublicIpAddress' \
              --filters "Name=tag:Project,Values=udacity" \
              --output text >> ~/inventory
      - persist_to_workspace:
          root: ~/
          paths:
            - inventory
  print_inventory:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - attach_workspace:
          at: ~/
      - run: cat ~/inventory

  
workflows:
  run_workflow:
    jobs:
      - reusable_command
      - get_ec2_instance_ips
      - print_inventory:
          requires:
            - get_ec2_instance_ips

