version: 2.1
commands:
  print_pipeline_id:
    description:
    steps:
      - run: echo ${CIRCLE_WORKFLOW_ID}
jobs:
  reusable_command:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - print_pipeline_id
  deliberate_fail:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run: return 1
      - run:
          name: on_failure
          command: echo "Hello Error!"
          when: on_fail
  
workflows:
  run_workflow:
    jobs:
      - reusable_command
      - deliberate_fail

